### PR TITLE
Created client class

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rickerc** [comment]
+1

**Comment by markvoelker** [comment]
There are a couple of puppet-lint errors in here that it would be nice to tidy up, but otherwise looks good.

WARNING: top-scope variable being used without an explicit namespace on line 10
ERROR: trailing whitespace found on line 22
ERROR: trailing whitespace found on line 116
WARNING: line 64 has more than 80 characters
WARNING: => on line 84 isn't aligned with the previous line
WARNING: => on line 89 isn't aligned with the previous line
WARNING: line 106 has more than 80 characters
WARNING: line 114 has more than 80 characters
WARNING: unquoted file mode on line 19
WARNING: unquoted file mode on line 27
WARNING: unquoted file mode on line 35
WARNING: unquoted file mode on line 43
WARNING: unquoted file mode on line 51
WARNING: unquoted file mode on line 59
WARNING: unquoted file mode on line 69

**Comment by ghost** [comment]
wow, that is pretty dirty. I have a newer puppet lint, so it complained about the variable encapsulation, so I added that in too. All is clean now. I used discretion on two of the line > 80 chars, as to break them up would be silly.

**Comment by markvoelker** [comment]
YEah, upstream gate jobs don't even check warnings IIRC, just errors.

**Comment by markvoelker** [comment]
+1 from me

**Pull request merged**
