### PR TITLE
ceph-deploy missing no-adjust-repos flag

### PR DESCRIPTION
**Pull request by rickerc**
ceph-deploy is missing the --no-adjust-repos flag so it will try to use
the Ceph master repos rather than the default preconfigured system repos
for package installation.

Additionally, paths are wrong in several Exec statements related to
ceph-deploy.

Partial-Bug: #1289569

### CODE REVIEW

**Comment by markvoelker** [comment]
+1

**Comment by ghost** [comment]
baseconfig isn't used anymore (it's client.pp now)

**Comment by ghost** [comment]
I'd prefer if you did a pull request upstream to just delete baseconfig.pp and mds.pp.

:-1:

**Comment by rickerc** [comment]
@dontalton How's that align with this?

https://github.com/CiscoSystems/puppet_openstack_builder/blob/coi-development/data/data_mappings/cinder_backend/rbd.yaml

ceph_deploy_password:
- cephdeploy::pass
- cephdeploy::baseconfig::pass
  ceph_deploy_user:
- cephdeploy::user
- cephdeploy::baseconfig::user

(and similar glance mappings)

**Comment by ghost** [comment]
Not sure. What happens when you map data to a class that's not in use?

**Comment by ghost** [comment]
My thoughts are:

rm -rf data/hiera_data/{cinder|glance}_backend (since this data sits in user.common.yaml)

set up the data mapping in data/data_mappings/{cinder|glance}_backend.

Then this can tie in with https://bugs.launchpad.net/openstack-cisco/+bug/1288307 in that I can dump the explicit hiera lookups.

edit: unless we agree ceph should be installable independent of cinder/glance usage.

**Comment by rickerc** [comment]
Closing - will be resolved by a refactoring to kill baseconfig, etc

**Pull request closed without merging**
